name: CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gradle-version: ["8.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew check
        env:
          GRADLE_VERSION_TO_TEST: ${{ matrix.gradle-version }}

  automerge-dependabot:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: allegro-actions/dependabot-automerge@v1