name: CI

on:
  push:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update version in README.md
        run: |
          # VERSION=$(cut -d "v" -f2 <<< ${{ github.ref_name }})
          VERSION=0.3.0
          echo "Updating README.md with version $VERSION"
          sed -Ei "s/(id\(\"dev\.panuszewski\.typesafe-conventions\"\) version \")[^\"]*(\")/\1$VERSION\2/" README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update version in README.md
          branch: main
          token: ${{ secrets.AUTO_COMMIT_PAT }}