name: Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - run: ./gradlew publishPlugins
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Update version in README.md
        run: |
          VERSION=$(cut -d "v" -f2 <<< ${{ github.ref_name }})
          echo "Updating README.md with version $VERSION"
          sed -Ei 's/(id\("dev\.panuszewski\.typesafe-conventions"\) version ")[^"]*(")/\11.0.0\2/' README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update version in README.md
          branch: main